<?xml version="1.0" encoding="utf-8"?><Database Name="NEPTUNE" Class="NeptuneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BESDBPROD2;Initial Catalog=NEPTUNE;Integrated Security=True" SettingsObjectName="Pinto.Properties.Settings" SettingsPropertyName="NEPTUNEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CYCLE_DATA" Member="CYCLE_DATAs">
    <Type Name="CYCLE_DATA">
      <Column Name="cycle_data_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="calendar_date_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_of_day_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="station_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pump_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cycle_change_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="onoff_state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="load_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="source_filename" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>